// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class GLink
{
	private static IGLink glink = null;
	
	public static IGLink sharedInstance() {
		if (glink == null) {
			#if UNITY_IOS
			glink = new GLinkiOS();
			#elif UNITY_ANDROID
			glink = new GLinkAndroid();
			#endif
		}

		return glink;
	}
}
