// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;

public class GLinkAndroid : IGLink {
	
	#if UNITY_ANDROID
	AndroidJavaClass ginkClass = null;
	AndroidJavaObject currentActivity = null;

	class OnClickAppSchemeBannerListener : AndroidJavaProxy {
		public OnClickAppSchemeBannerListener () : base("com.naver.glink.android.sdk.Glink$OnClickAppSchemeBannerListener") { /* empty. */ }

		void onClickAppSchemeBanner (string appScheme) {
			showToast ("tapped:" + appScheme);
		}
	}

	class OnSdkStartedListener : AndroidJavaProxy {
		public OnSdkStartedListener () : base("com.naver.glink.android.sdk.Glink$OnSdkStartedListener") { /* empty. */ }

		void onSdkStarted () {
			showToast ("sdk start.");
		}
	}

	class OnSdkStoppedListener : AndroidJavaProxy {
		public OnSdkStoppedListener () : base("com.naver.glink.android.sdk.Glink$OnSdkStoppedListener") { /* empty. */ }

		void onSdkStopped () {
			showToast ("sdk stop.");
		}
	}

	class OnLoggedInListener : AndroidJavaProxy {
		public OnLoggedInListener () : base("com.naver.glink.android.sdk.Glink$OnLoggedInListener") { /* empty. */ }

		void onLoggedIn (bool success) {
			showToast ("logged in:" + success);
		} 

	}

	static void showToast(string message) {
		var activity = new AndroidJavaClass ("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject> ("currentActivity");
		activity.Call ("runOnUiThread", new AndroidJavaRunnable (() => {
			AndroidJavaObject toast = new AndroidJavaClass ("android.widget.Toast").CallStatic<AndroidJavaObject>("makeText", activity, message, 1);
			toast.Call ("show");
		}));
	}
	#endif

	public GLinkAndroid () {
		#if UNITY_ANDROID
		currentActivity = new AndroidJavaClass ("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject> ("currentActivity");
		ginkClass = new AndroidJavaClass ("com.naver.glink.android.sdk.Glink");
		ginkClass.CallStatic ("init", GLinkConfig.NaverLoginClientId, GLinkConfig.NaverLoginClientSecret, GLinkConfig.CafeId);

		// 앱스킴 listener 사용 하려면 아래 주석을 풀어 주세요.
		// ginkClass.CallStatic ("setOnClickAppSchemeBannerListener", new OnClickAppSchemeBannerListener ());

		// sdk start listener 사용 하려면 아래 주석을 풀어 주세요.
		// ginkClass.CallStatic ("setOnSdkStartedListener", new OnSdkStartedListener ());

		// sdk stop listener 사용 하려면 아래 주석을 풀어 주세요.
		// ginkClass.CallStatic ("setOnSdkStoppedListener", new OnSdkStoppedListener ());

		// 게임 아이디 연동을 하려면 아래 주석을 풀어 주세요.
		// setGameUserId ("yourGameId", "");
		#endif
	}

	public void executeHome() {
		#if UNITY_ANDROID
		ginkClass.CallStatic("startHome", currentActivity);
		#endif
	}

	public void executeNotice() {
		#if UNITY_ANDROID
		ginkClass.CallStatic("startNotice", currentActivity);
		#endif
	}

	public void executeEvent() {
		#if UNITY_ANDROID
		ginkClass.CallStatic("startEvent", currentActivity);
		#endif
	}

	public void executeMenu() {
		#if UNITY_ANDROID
		ginkClass.CallStatic("startMenu", currentActivity);
		#endif
	}

	public void executeProfile() {
		#if UNITY_ANDROID
		ginkClass.CallStatic("startProfile", currentActivity);
		#endif
	}

	public void executeArticle (int articleId) {
		#if UNITY_ANDROID
		ginkClass.CallStatic("startArticle", currentActivity, articleId);
		#endif
	}

	public void executeArticlePost(int menuId, string subject, string content) {
		#if UNITY_ANDROID
		ginkClass.CallStatic ("startWrite", currentActivity, menuId, subject, content);
		#endif
	}

	public void executeArticlePostWithImage(int menuId, string subject, string content, string filePath) {
		#if UNITY_ANDROID
		ginkClass.CallStatic ("startImageWrite", currentActivity, menuId, subject, content, "file://" + filePath);
		#endif
	}

	public void executeArticlePostWithVideo(int menuId, string subject, string content, string filePath) {
		#if UNITY_ANDROID
		ginkClass.CallStatic ("startVideoWrite", currentActivity, subject, content, "file://" + filePath);
		#endif
	}

	public void setGameUserId (string gameUserId, string fieldName) {
		#if UNITY_ANDROID
		ginkClass.CallStatic ("setGameUserId", currentActivity, gameUserId, fieldName);
		#endif
	}
}
