// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class GLinkUnity
{
	private static IGLink mGLink = null;
	
	public static IGLink sharedInstance() {
		if (mGLink == null) {
			#if UNITY_IOS
			mGLink = new GLinkiOS();
			#elif UNITY_ANDROID
			mGLink = new GLinkAndroid();
			#endif
		}

		return mGLink;
	}

	public static void executeMain() {
		sharedInstance().executeMain ();
	}
	
	public static void executeArticlePost(int menuId, string subject, string content) {
		sharedInstance().executeArticlePost (menuId, subject, content);
	}
	
	public static void executeArticlePostWithImage(int menuId, string subject, string content, string filePath) {
		sharedInstance().executeArticlePostWithImage (menuId, subject, content, filePath);
	}
	
	public static void executeArticlePostWithVideo(int menuId, string subject, string content, string filePath) {
		sharedInstance().executeArticlePostWithVideo (menuId, subject, content, filePath);
	}
}


