// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

public class GLinkiOS : IGLink
{
	#if UNITY_IPHONE
	[DllImport("__Internal")]
	public static extern void _InitGLink(string consumerKey, string consumerSecret, int cafeId);

	[DllImport("__Internal")]
	public static extern void _ExecuteMain();
	
	[DllImport("__Internal")]
	public static extern void _ExecuteArticlePost(int menuId, string subject, string content);
	
	[DllImport("__Internal")]
	public static extern void _ExecuteArticlePostWithImage(int menuId, string subject, string content, string filePath);
	
	[DllImport("__Internal")]
	public static extern void _ExecuteArticlePostWithVideo(int menuId, string subject, string content, string filePath);
	#endif

	public GLinkiOS() {
		#if UNITY_IPHONE
		_InitGLink(GLinkConfig.NaverLoginClientId, GLinkConfig.NaverLoginClientSecret, GLinkConfig.CafeId);
		#endif
	}

	public void executeMain() {
		#if UNITY_IPHONE 
		_ExecuteMain ();
		#endif
	}
	
	public void executeArticlePost(int menuId, string subject, string content) {
		#if UNITY_IPHONE
		_ExecuteArticlePost(menuId, subject, content);
		#endif
	}

	public void executeArticlePostWithImage(int menuId, string subject, string content, string filePath) {
		#if UNITY_IPHONE
		_ExecuteArticlePostWithImage(menuId, subject, content, filePath);
		#endif
	}
	
	public void executeArticlePostWithVideo(int menuId, string subject, string content, string filePath) {
		#if UNITY_IPHONE
		_ExecuteArticlePostWithVideo(menuId, subject, content, filePath);
		#endif
	}
}


