// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

public interface IGLink
{
	void executeMain();
	
	void executeArticlePost(int menuId, string subject, string content);
	
	void executeArticlePostWithImage(int menuId, string subject, string content, string filePath);

	void executeArticlePostWithVideo(int menuId, string subject, string content, string filePath);
}


